New features
scaleway-terraform-modules/terraform-scaleway-bucket pull request #16
Opened 2023-05-09 08:50 UTC by lotusnoir

adding new features for S3 buckets

2023-05-20 09:53 UTC, benoit-garcia requested changes
Hello,
Thanks for your contribution!
There's a few things that could be improved before merging, I made some suggestions.
Let me know if I can help with them.

2023-05-20 09:53 UTC, benoit-garcia commented on README.md
> +
Could you move this example to a dedicated sub-folder? You can refer to Hashicorp [Standard Module Structure](https://developer.hashicorp.com/terraform/language/modules/develop/structure) for this.

2023-05-20 09:53 UTC, benoit-garcia commented on main.tf
> +resource "scaleway_object_bucket" "main" {
Ok to renamed, not adding a "moved" block will break users. Should be:
```suggestion
moved {
  from = scaleway_object_bucket.this
  to   = scaleway_object_bucket.main
}

resource "scaleway_object_bucket" "main" {
```

2023-05-20 09:53 UTC, benoit-garcia commented on main.tf
> +resource "scaleway_object_bucket_lock_configuration" "main" {
Same than before: Add a "moved" block. Should be:
```suggestion
moved {
  from = scaleway_object_bucket_lock_configuration.this
  to   = scaleway_object_bucket_lock_configuration.main
}

resource "scaleway_object_bucket_lock_configuration" "main" {
```

2023-05-20 09:53 UTC, benoit-garcia commented on versions.tf
> +      version = ">= 2.17.0"
I'm not sure there's a lot of changes on bucket related resources since v2.10.0. Should be:
```suggestion
      version = ">= 2.10.0"
```

2023-05-20 09:53 UTC, benoit-garcia commented on versions.tf
> +  required_version = ">= 1.3.7"
```suggestion
  required_version = ">= 1.3"
```

2023-05-24 08:15 UTC, lotusnoir commented on README.md
> +
ok i'll make a separate commit to not block this one

2024-03-28 14:10 UTC, jgalais commented
Hello,

Thank you @lotusnoir  and @benoit-garcia for your job.

@benoit-garcia Can you validate this Pull request ?

I want to create S3 bucket but tag usage it's an important thing.
I try to avoid to fork all Scaleway module to avoid to recreate the wheel each time.

Regards,

2024-04-01 19:31 UTC, benoit-garcia commented
Hello,

@jgalais 
I've added support of tags on [v2.0.0](https://github.com/scaleway-terraform-modules/terraform-scaleway-bucket/releases/tag/v0.2.0). Feel free to test and let me know.

@lotusnoir 
Thanks for you work. I'd like to maintain some consistency on code style.
As I couldn't edit your pull request, I create #34 based on your code and improved/cleaned it a little.
Hope you won't mind; your contributions are highly appreciated.

2024-04-01 19:31 UTC, closed without merging

2024-04-02 07:55 UTC, jgalais commented
Hello,

I tested this morning and tags function is ok.

Thank you.

Regards,